command: [
  "uvicorn"
  ,"app:app"
  ,"--host"
  ,"0.0.0.0"
  ,"--port"
  ,"8000"
  ,"--log-level"
  ,"info"
]

env: 

  - name: ZEROBUS_CLIENT_ID
    valueFrom: zerobus_client_id

  - name: ZEROBUS_CLIENT_SECRET
    valueFrom: zerobus_client_secret

  - name: ZEROBUS_SERVER_ENDPOINT
    valueFrom: zerobus_endpoint

  - name: WORKSPACE_URL
    valueFrom: workspace_url

  - name: FHIR_BUNDLE_TABLE_NAME
    valueFrom: fhir_bundle_table_name
  
  - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
    value: cpp

  