# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fhir_bundle.proto
# Protobuf Python Version: 5.29.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    6,
    '',
    'fhir_bundle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66hir_bundle.proto\x12\x04\x66hir\"s\n\nFhirBundle\x12\x13\n\x0b\x62undle_uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x66hir\x18\x02 \x01(\t\x12\x15\n\rsource_system\x18\x03 \x01(\t\x12\x17\n\x0f\x65vent_timestamp\x18\x04 \x01(\x03\x12\x12\n\nuser_email\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fhir_bundle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FHIRBUNDLE']._serialized_start=27
  _globals['_FHIRBUNDLE']._serialized_end=142
# @@protoc_insertion_point(module_scope)
